version: '3.8'

volumes:
  postgres-db-volume:

services:

######################################################
# AIRFLOW
######################################################

  airflow:
    build: 
      context: ./docker/airflow
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./docker/airflow/dags:/opt/airflow/dags
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10

######################################################
# POSTGRES
######################################################

  postgres:
    build: 
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

######################################################
# ADMINER (optional)
######################################################

  adminer:
    build:
      context: './docker/adminer'
      dockerfile: ./Dockerfile
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - 9000:9000
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=airflow
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10
    depends_on:
      - postgres